CLIENT = Client/Makefile
SERVER = Server/Makefile

#call all from Client/Makefile and Server/Makefile
all:

#call clean from Client/Makefile and Server/Makefile
clean:

#call fclean from Client/Makefile and Server/Makefile
fclean:

#call re from Client/Makefile and Server/Makefile
re:

#call all from Client/Makefile
client_all:

#call clean from Client/Makefile
client_clean:

#call fclean from Client/Makefile
client_fclean:

#call re from Client/Makefile
client_re:

#call all from Server/Makefile
server_all:

#call clean from Server/Makefile
server_clean:

#call fclean from Server/Makefile
server_fclean:

#call re from Server/Makefile
server_re:
